plugins {
    id 'com.android.application'
}

android {
    namespace 'com.forexpilot.ai'
    compileSdk 36

    defaultConfig {
        applicationId "com.forexpilot.ai"
        minSdk 23
        targetSdk 36
        versionCode 2
        versionName "2.0.0"

        def key = project.findProperty('TWELVE_DATA_API_KEY') ?:
                System.getenv('TWELVE_DATA_API_KEY') ?: ''

        buildConfigField(
                'String',
                'TWELVE_DATA_API_KEY',
                '"' + key.replace('\\', '\\\\')
                        .replace('"', '\\"') + '"'
        )
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'

    // Chart library
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
}
